import type { CaptionStyleId, Word } from './types.js';
import { layoutCaptions, type CaptionLine } from './captionLayout.js';

/** Brand palette in ASS colour notation (&HAABBGGRR). */
export const ASS_COLOURS = {
  cream: '&H00F3F9FD',
  lime: '&H003DFFC8',
  purple: '&H00FF5C7B',
  ink: '&H0014171A',
  inkSoft: '&H5014171A',
} as const;

export interface AssOptions {
  width: number;
  height: number;
  style: CaptionStyleId;
  uppercase?: boolean;
  fontName?: string;
  /** Multiplier on the automatic font size. */
  fontScale?: number;
  maxWords?: number;
}

function assTime(t: number): string {
  const cs = Math.round(Math.max(0, t) * 100);
  const h = Math.floor(cs / 360000);
  const m = Math.floor((cs % 360000) / 6000);
  const s = Math.floor((cs % 6000) / 100);
  const c = cs % 100;
  return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(c).padStart(2, '0')}`;
}

export function escapeAssText(text: string): string {
  return text.replace(/\\/g, '/').replace(/\{/g, '(').replace(/\}/g, ')').replace(/\n/g, ' ');
}

function dialogue(start: number, end: number, text: string, style = 'Main'): string {
  return `Dialogue: 0,${assTime(start)},${assTime(end)},${style},,0,0,0,,${text}`;
}

function wordEvents(line: CaptionLine, render: (activeIdx: number) => string): string[] {
  const events: string[] = [];
  line.words.forEach((w, i) => {
    const next = line.words[i + 1];
    const start = i === 0 ? line.start : w.start;
    const end = next ? next.start : line.end;
    if (end - start > 0.005) events.push(dialogue(start, end, render(i)));
  });
  return events;
}

/** Builds an Advanced SubStation Alpha script with animated, brand-coloured captions. */
export function buildAss(words: Word[], opts: AssOptions): string {
  const { width, height, style } = opts;
  const vertical = height > width;
  const base = Math.min(width, height);
  const fontScale = opts.fontScale ?? 1;
  const minimal = style === 'minimal';
  const fontSize = Math.round(base * (minimal ? 0.05 : vertical ? 0.1 : 0.07) * fontScale);
  const marginV = Math.round(height * (minimal ? 0.06 : vertical ? 0.26 : 0.1));
  const outline = minimal ? Math.max(2, Math.round(fontSize * 0.18)) : Math.max(3, Math.round(fontSize * 0.09));
  const fontName = opts.fontName ?? 'Arial';
  const borderStyle = minimal ? 3 : 1;
  const primary = style === 'karaoke' ? ASS_COLOURS.lime : ASS_COLOURS.cream;
  const secondary = style === 'karaoke' ? ASS_COLOURS.cream : ASS_COLOURS.lime;
  const outlineColour = minimal ? ASS_COLOURS.inkSoft : ASS_COLOURS.ink;

  const header = [
    '[Script Info]',
    '; Generated by kerfreel',
    'ScriptType: v4.00+',
    `PlayResX: ${width}`,
    `PlayResY: ${height}`,
    'WrapStyle: 0',
    'ScaledBorderAndShadow: yes',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    `Style: Main,${fontName},${fontSize},${primary},${secondary},${outlineColour},${ASS_COLOURS.inkSoft},${minimal ? 0 : -1},0,0,0,100,100,0,0,${borderStyle},${outline},${minimal ? 0 : 2},2,${Math.round(width * 0.06)},${Math.round(width * 0.06)},${marginV},1`,
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ];
  if (style === 'none' || words.length === 0) return header.join('\n') + '\n';

  const lines = layoutCaptions(words, { maxWords: opts.maxWords ?? (minimal ? 8 : vertical ? 3 : 5), maxChars: minimal ? 42 : vertical ? 18 : 30 });
  const fmt = (t: string) => escapeAssText(opts.uppercase ? t.toUpperCase() : t);
  const events: string[] = [];

  for (const line of lines) {
    const texts = line.words.map((w) => fmt(w.text));
    switch (style) {
      case 'pop':
        events.push(
          ...wordEvents(line, (active) =>
            texts
              .map((t, i) =>
                i === active ? `{\\c${ASS_COLOURS.lime}&\\fscx100\\fscy100\\t(0,80,\\fscx118\\fscy118)\\t(80,170,\\fscx108\\fscy108)}${t}{\\r}` : t,
              )
              .join(' '),
          ),
        );
        break;
      case 'glow':
        events.push(
          ...wordEvents(line, (active) =>
            texts.map((t, i) => (i === active ? `{\\3c${ASS_COLOURS.purple}&\\bord${outline * 2}\\blur6}${t}{\\r}` : `{\\alpha&H30&}${t}{\\r}`)).join(' '),
          ),
        );
        break;
      case 'bounce':
        events.push(
          ...wordEvents(line, (active) =>
            texts
              .slice(0, active + 1)
              .map((t, i) =>
                i === active ? `{\\c${ASS_COLOURS.lime}&\\fscx45\\fscy45\\t(0,110,\\fscx106\\fscy106)\\t(110,180,\\fscx100\\fscy100)}${t}{\\r}` : t,
              )
              .join(' '),
          ),
        );
        break;
      case 'karaoke': {
        let cursor = line.start;
        const parts = line.words.map((w, i) => {
          const lead = Math.max(0, Math.round((w.start - cursor) * 100));
          const dur = Math.max(1, Math.round((w.end - w.start) * 100));
          cursor = w.end;
          return `${lead ? `{\\k${lead}}` : ''}{\\kf${dur}}${texts[i]}`;
        });
        events.push(dialogue(line.start, line.end, `{\\fad(60,60)}${parts.join(' ')}`));
        break;
      }
      case 'minimal':
      default:
        events.push(dialogue(line.start, line.end, `{\\fad(80,80)}${texts.join(' ')}`));
        break;
    }
  }
  return [...header, ...events].join('\n') + '\n';
}
